//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.34209
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTestWebBack.MyCardTagSettingWCF {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyCardTagSettingWCF.IService1")]
    public interface IService1 {
        
        // CODEGEN: 參數 'MSM_View_GetStoreTagResult' 需要無法以參數模式來擷取的其他架構資訊。特定屬性為 'System.Xml.Serialization.XmlElementAttribute'。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MSM_View_GetStoreTag", ReplyAction="http://tempuri.org/IService1/MSM_View_GetStoreTagResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MyTestWebBack.MyCardTagSettingWCF.MSM_View_GetStoreTagResponse MSM_View_GetStoreTag(MyTestWebBack.MyCardTagSettingWCF.MSM_View_GetStoreTagRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MSM_View_GetStoreTag", ReplyAction="http://tempuri.org/IService1/MSM_View_GetStoreTagResponse")]
        System.Threading.Tasks.Task<MyTestWebBack.MyCardTagSettingWCF.MSM_View_GetStoreTagResponse> MSM_View_GetStoreTagAsync(MyTestWebBack.MyCardTagSettingWCF.MSM_View_GetStoreTagRequest request);
        
        // CODEGEN: 參數 'MSM_SP_StoreTagInsertResult' 需要無法以參數模式來擷取的其他架構資訊。特定屬性為 'System.Xml.Serialization.XmlElementAttribute'。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MSM_SP_StoreTagInsert", ReplyAction="http://tempuri.org/IService1/MSM_SP_StoreTagInsertResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MyTestWebBack.MyCardTagSettingWCF.MSM_SP_StoreTagInsertResponse MSM_SP_StoreTagInsert(MyTestWebBack.MyCardTagSettingWCF.MSM_SP_StoreTagInsertRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MSM_SP_StoreTagInsert", ReplyAction="http://tempuri.org/IService1/MSM_SP_StoreTagInsertResponse")]
        System.Threading.Tasks.Task<MyTestWebBack.MyCardTagSettingWCF.MSM_SP_StoreTagInsertResponse> MSM_SP_StoreTagInsertAsync(MyTestWebBack.MyCardTagSettingWCF.MSM_SP_StoreTagInsertRequest request);
        
        // CODEGEN: 參數 'MSM_SP_StoreTagUpdateResult' 需要無法以參數模式來擷取的其他架構資訊。特定屬性為 'System.Xml.Serialization.XmlElementAttribute'。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MSM_SP_StoreTagUpdate", ReplyAction="http://tempuri.org/IService1/MSM_SP_StoreTagUpdateResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MyTestWebBack.MyCardTagSettingWCF.MSM_SP_StoreTagUpdateResponse MSM_SP_StoreTagUpdate(MyTestWebBack.MyCardTagSettingWCF.MSM_SP_StoreTagUpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MSM_SP_StoreTagUpdate", ReplyAction="http://tempuri.org/IService1/MSM_SP_StoreTagUpdateResponse")]
        System.Threading.Tasks.Task<MyTestWebBack.MyCardTagSettingWCF.MSM_SP_StoreTagUpdateResponse> MSM_SP_StoreTagUpdateAsync(MyTestWebBack.MyCardTagSettingWCF.MSM_SP_StoreTagUpdateRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/MyCardTagSettingWCF")]
    public partial class ReturnValue : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Data.DataSet returnDataSetField;
        
        private string returnMsgField;
        
        private int returnMsgNoField;
        
        private bool returnMsgNoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Data.DataSet ReturnDataSet {
            get {
                return this.returnDataSetField;
            }
            set {
                this.returnDataSetField = value;
                this.RaisePropertyChanged("ReturnDataSet");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string ReturnMsg {
            get {
                return this.returnMsgField;
            }
            set {
                this.returnMsgField = value;
                this.RaisePropertyChanged("ReturnMsg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int ReturnMsgNo {
            get {
                return this.returnMsgNoField;
            }
            set {
                this.returnMsgNoField = value;
                this.RaisePropertyChanged("ReturnMsgNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReturnMsgNoSpecified {
            get {
                return this.returnMsgNoFieldSpecified;
            }
            set {
                this.returnMsgNoFieldSpecified = value;
                this.RaisePropertyChanged("ReturnMsgNoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MSM_View_GetStoreTag", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class MSM_View_GetStoreTagRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TagName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Status;
        
        public MSM_View_GetStoreTagRequest() {
        }
        
        public MSM_View_GetStoreTagRequest(string TagName, string Status) {
            this.TagName = TagName;
            this.Status = Status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MSM_View_GetStoreTagResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class MSM_View_GetStoreTagResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MyTestWebBack.MyCardTagSettingWCF.ReturnValue MSM_View_GetStoreTagResult;
        
        public MSM_View_GetStoreTagResponse() {
        }
        
        public MSM_View_GetStoreTagResponse(MyTestWebBack.MyCardTagSettingWCF.ReturnValue MSM_View_GetStoreTagResult) {
            this.MSM_View_GetStoreTagResult = MSM_View_GetStoreTagResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MSM_SP_StoreTagInsert", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class MSM_SP_StoreTagInsertRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TagName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StoreTagURL;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int State;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ImageURL;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public int Priority;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CreateUser;
        
        public MSM_SP_StoreTagInsertRequest() {
        }
        
        public MSM_SP_StoreTagInsertRequest(string TagName, string StoreTagURL, int State, string ImageURL, int Priority, string CreateUser) {
            this.TagName = TagName;
            this.StoreTagURL = StoreTagURL;
            this.State = State;
            this.ImageURL = ImageURL;
            this.Priority = Priority;
            this.CreateUser = CreateUser;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MSM_SP_StoreTagInsertResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class MSM_SP_StoreTagInsertResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MyTestWebBack.MyCardTagSettingWCF.ReturnValue MSM_SP_StoreTagInsertResult;
        
        public MSM_SP_StoreTagInsertResponse() {
        }
        
        public MSM_SP_StoreTagInsertResponse(MyTestWebBack.MyCardTagSettingWCF.ReturnValue MSM_SP_StoreTagInsertResult) {
            this.MSM_SP_StoreTagInsertResult = MSM_SP_StoreTagInsertResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MSM_SP_StoreTagUpdate", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class MSM_SP_StoreTagUpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int StoreTagSn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TagName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StoreTagURL;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int State;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ImageURL;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public int Priority;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UserStamp;
        
        public MSM_SP_StoreTagUpdateRequest() {
        }
        
        public MSM_SP_StoreTagUpdateRequest(int StoreTagSn, string TagName, string StoreTagURL, int State, string ImageURL, int Priority, string UserStamp) {
            this.StoreTagSn = StoreTagSn;
            this.TagName = TagName;
            this.StoreTagURL = StoreTagURL;
            this.State = State;
            this.ImageURL = ImageURL;
            this.Priority = Priority;
            this.UserStamp = UserStamp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MSM_SP_StoreTagUpdateResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class MSM_SP_StoreTagUpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MyTestWebBack.MyCardTagSettingWCF.ReturnValue MSM_SP_StoreTagUpdateResult;
        
        public MSM_SP_StoreTagUpdateResponse() {
        }
        
        public MSM_SP_StoreTagUpdateResponse(MyTestWebBack.MyCardTagSettingWCF.ReturnValue MSM_SP_StoreTagUpdateResult) {
            this.MSM_SP_StoreTagUpdateResult = MSM_SP_StoreTagUpdateResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : MyTestWebBack.MyCardTagSettingWCF.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<MyTestWebBack.MyCardTagSettingWCF.IService1>, MyTestWebBack.MyCardTagSettingWCF.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyTestWebBack.MyCardTagSettingWCF.MSM_View_GetStoreTagResponse MyTestWebBack.MyCardTagSettingWCF.IService1.MSM_View_GetStoreTag(MyTestWebBack.MyCardTagSettingWCF.MSM_View_GetStoreTagRequest request) {
            return base.Channel.MSM_View_GetStoreTag(request);
        }
        
        public MyTestWebBack.MyCardTagSettingWCF.ReturnValue MSM_View_GetStoreTag(string TagName, string Status) {
            MyTestWebBack.MyCardTagSettingWCF.MSM_View_GetStoreTagRequest inValue = new MyTestWebBack.MyCardTagSettingWCF.MSM_View_GetStoreTagRequest();
            inValue.TagName = TagName;
            inValue.Status = Status;
            MyTestWebBack.MyCardTagSettingWCF.MSM_View_GetStoreTagResponse retVal = ((MyTestWebBack.MyCardTagSettingWCF.IService1)(this)).MSM_View_GetStoreTag(inValue);
            return retVal.MSM_View_GetStoreTagResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyTestWebBack.MyCardTagSettingWCF.MSM_View_GetStoreTagResponse> MyTestWebBack.MyCardTagSettingWCF.IService1.MSM_View_GetStoreTagAsync(MyTestWebBack.MyCardTagSettingWCF.MSM_View_GetStoreTagRequest request) {
            return base.Channel.MSM_View_GetStoreTagAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyTestWebBack.MyCardTagSettingWCF.MSM_View_GetStoreTagResponse> MSM_View_GetStoreTagAsync(string TagName, string Status) {
            MyTestWebBack.MyCardTagSettingWCF.MSM_View_GetStoreTagRequest inValue = new MyTestWebBack.MyCardTagSettingWCF.MSM_View_GetStoreTagRequest();
            inValue.TagName = TagName;
            inValue.Status = Status;
            return ((MyTestWebBack.MyCardTagSettingWCF.IService1)(this)).MSM_View_GetStoreTagAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyTestWebBack.MyCardTagSettingWCF.MSM_SP_StoreTagInsertResponse MyTestWebBack.MyCardTagSettingWCF.IService1.MSM_SP_StoreTagInsert(MyTestWebBack.MyCardTagSettingWCF.MSM_SP_StoreTagInsertRequest request) {
            return base.Channel.MSM_SP_StoreTagInsert(request);
        }
        
        public MyTestWebBack.MyCardTagSettingWCF.ReturnValue MSM_SP_StoreTagInsert(string TagName, string StoreTagURL, int State, string ImageURL, int Priority, string CreateUser) {
            MyTestWebBack.MyCardTagSettingWCF.MSM_SP_StoreTagInsertRequest inValue = new MyTestWebBack.MyCardTagSettingWCF.MSM_SP_StoreTagInsertRequest();
            inValue.TagName = TagName;
            inValue.StoreTagURL = StoreTagURL;
            inValue.State = State;
            inValue.ImageURL = ImageURL;
            inValue.Priority = Priority;
            inValue.CreateUser = CreateUser;
            MyTestWebBack.MyCardTagSettingWCF.MSM_SP_StoreTagInsertResponse retVal = ((MyTestWebBack.MyCardTagSettingWCF.IService1)(this)).MSM_SP_StoreTagInsert(inValue);
            return retVal.MSM_SP_StoreTagInsertResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyTestWebBack.MyCardTagSettingWCF.MSM_SP_StoreTagInsertResponse> MyTestWebBack.MyCardTagSettingWCF.IService1.MSM_SP_StoreTagInsertAsync(MyTestWebBack.MyCardTagSettingWCF.MSM_SP_StoreTagInsertRequest request) {
            return base.Channel.MSM_SP_StoreTagInsertAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyTestWebBack.MyCardTagSettingWCF.MSM_SP_StoreTagInsertResponse> MSM_SP_StoreTagInsertAsync(string TagName, string StoreTagURL, int State, string ImageURL, int Priority, string CreateUser) {
            MyTestWebBack.MyCardTagSettingWCF.MSM_SP_StoreTagInsertRequest inValue = new MyTestWebBack.MyCardTagSettingWCF.MSM_SP_StoreTagInsertRequest();
            inValue.TagName = TagName;
            inValue.StoreTagURL = StoreTagURL;
            inValue.State = State;
            inValue.ImageURL = ImageURL;
            inValue.Priority = Priority;
            inValue.CreateUser = CreateUser;
            return ((MyTestWebBack.MyCardTagSettingWCF.IService1)(this)).MSM_SP_StoreTagInsertAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyTestWebBack.MyCardTagSettingWCF.MSM_SP_StoreTagUpdateResponse MyTestWebBack.MyCardTagSettingWCF.IService1.MSM_SP_StoreTagUpdate(MyTestWebBack.MyCardTagSettingWCF.MSM_SP_StoreTagUpdateRequest request) {
            return base.Channel.MSM_SP_StoreTagUpdate(request);
        }
        
        public MyTestWebBack.MyCardTagSettingWCF.ReturnValue MSM_SP_StoreTagUpdate(int StoreTagSn, string TagName, string StoreTagURL, int State, string ImageURL, int Priority, string UserStamp) {
            MyTestWebBack.MyCardTagSettingWCF.MSM_SP_StoreTagUpdateRequest inValue = new MyTestWebBack.MyCardTagSettingWCF.MSM_SP_StoreTagUpdateRequest();
            inValue.StoreTagSn = StoreTagSn;
            inValue.TagName = TagName;
            inValue.StoreTagURL = StoreTagURL;
            inValue.State = State;
            inValue.ImageURL = ImageURL;
            inValue.Priority = Priority;
            inValue.UserStamp = UserStamp;
            MyTestWebBack.MyCardTagSettingWCF.MSM_SP_StoreTagUpdateResponse retVal = ((MyTestWebBack.MyCardTagSettingWCF.IService1)(this)).MSM_SP_StoreTagUpdate(inValue);
            return retVal.MSM_SP_StoreTagUpdateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyTestWebBack.MyCardTagSettingWCF.MSM_SP_StoreTagUpdateResponse> MyTestWebBack.MyCardTagSettingWCF.IService1.MSM_SP_StoreTagUpdateAsync(MyTestWebBack.MyCardTagSettingWCF.MSM_SP_StoreTagUpdateRequest request) {
            return base.Channel.MSM_SP_StoreTagUpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyTestWebBack.MyCardTagSettingWCF.MSM_SP_StoreTagUpdateResponse> MSM_SP_StoreTagUpdateAsync(int StoreTagSn, string TagName, string StoreTagURL, int State, string ImageURL, int Priority, string UserStamp) {
            MyTestWebBack.MyCardTagSettingWCF.MSM_SP_StoreTagUpdateRequest inValue = new MyTestWebBack.MyCardTagSettingWCF.MSM_SP_StoreTagUpdateRequest();
            inValue.StoreTagSn = StoreTagSn;
            inValue.TagName = TagName;
            inValue.StoreTagURL = StoreTagURL;
            inValue.State = State;
            inValue.ImageURL = ImageURL;
            inValue.Priority = Priority;
            inValue.UserStamp = UserStamp;
            return ((MyTestWebBack.MyCardTagSettingWCF.IService1)(this)).MSM_SP_StoreTagUpdateAsync(inValue);
        }
    }
}
